### ISSUE TITLE
Having trouble running demos with video renderer on MacOS

### ISSUE THREAD

**Issue by ballagas** [daily-co/daily-python#30]
For the gtk demo, I get:
```
gtk % RUST_BACKTRACE=1 python gtk_app.py
2024-12-09 17:09:45.680 python[82862:75046502] +[IMKClient subclass]: chose IMKClient_Modern
thread '<unnamed>' panicked at /Users/runner/actions-runner/_work/daily-x/daily-x/daily-core/src/native/ffi/call_client/participants.rs:345:64:
called `Result::unwrap()` on an `Err` value: Error(Char { character: 'T', index: 1 })
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: _daily_core_call_client_set_participant_video_renderer
   4: daily::call_client::PyCallClient::set_video_renderer
   5: daily::call_client::PyCallClient::__pymethod_set_video_renderer__
   6: pyo3::impl_::trampoline::trampoline
   7: daily::call_client::<impl pyo3::impl_::pyclass::PyMethods<daily::call_client::PyCallClient> for pyo3::impl_::pyclass::PyClassImplCollector<daily::call_client::PyCallClient>>::py_methods::ITEMS::trampoline
   8: _method_vectorcall_VARARGS_KEYWORDS
   9: __PyEval_EvalFrameDefault
  10: _method_vectorcall
  11: _pygi_signal_closure_marshal
  12: _g_closure_invoke
  13: _signal_emit_unlocked_R
  14: _signal_emit_valist_unlocked
  15: _g_signal_emit_valist
  16: _g_signal_emit
  17: __gtk_marshal_VOID__INT_DOUBLE_DOUBLEv
  18: __g_closure_invoke_va
  19: _signal_emit_valist_unlocked
  20: _g_signal_emit_valist
  21: _g_signal_emit
  22: _gtk_gesture_click_end
  23: _g_cclosure_marshal_VOID__BOXEDv
  24: __g_closure_invoke_va
  25: _signal_emit_valist_unlocked
  26: _g_signal_emit_valist
  27: _g_signal_emit
  28: __gtk_gesture_set_recognized
  29: __gtk_gesture_check_recognized
  30: _gtk_gesture_handle_event
  31: _gtk_gesture_single_handle_event
  32: _gtk_event_controller_handle_event
  33: _gtk_widget_run_controllers
  34: __gtk_widget_captured_event
  35: _gtk_propagate_event_internal
  36: _gtk_main_do_event
  37: __gdk_marshal_BOOLEAN__POINTERv
  38: _gdk_surface_event_marshallerv
  39: __g_closure_invoke_va
  40: _signal_emit_valist_unlocked
  41: _g_signal_emit_valist
  42: _g_signal_emit
  43: _gdk_surface_handle_event
  44: _gdk_macos_event_source_dispatch
  45: _g_main_context_dispatch_unlocked
  46: _g_main_context_iterate_unlocked
  47: _g_main_context_iteration
  48: _g_application_run
  49: <unknown>
  50: <unknown>
  51: _pygi_invoke_c_callable
  52: _pygi_function_cache_invoke
  53: __PyEval_EvalFrameDefault
  54: _PyEval_EvalCode
  55: _run_mod
  56: _pyrun_file
  57: __PyRun_SimpleFileObject
  58: __PyRun_AnyFileObject
  59: _pymain_run_file_obj
  60: _pymain_run_file
  61: _Py_RunMain
  62: _pymain_main
  63: _main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread '<unnamed>' panicked at core/src/panicking.rs:221:5:
panic in a function that cannot unwind
stack backtrace:
   0:        0x1041b6e0c - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::habbf9c4f641febb1
   1:        0x1041d43d4 - core::fmt::write::ha36a8060c13608ea
   2:        0x1041b411c - std::io::Write::write_fmt::h431832c8ebcc85c9
   3:        0x1041b7f88 - std::panicking::default_hook::{{closure}}::h4aa1f60327dfff6a
   4:        0x1041b7b38 - std::panicking::default_hook::h4ebc6eb4ae179807
   5:        0x1041b8a04 - std::panicking::rust_panic_with_hook::h6a84efe4dcab239c
   6:        0x1041b8408 - std::panicking::begin_panic_handler::{{closure}}::h5eef292190467fef
   7:        0x1041b72d0 - std::sys::backtrace::__rust_end_short_backtrace::hd7e7925203f20af9
   8:        0x1041b80f8 - _rust_begin_unwind
   9:        0x10421b31c - core::panicking::panic_nounwind_fmt::hb2df5b6c3d6ab15b
  10:        0x10421b394 - core::panicking::panic_nounwind::h6b53a509f430e184
  11:        0x10421b480 - core::panicking::panic_cannot_unwind::hce6968fadcdebaaa
  12:        0x1036049a0 - _daily_core_call_client_set_participant_video_renderer
  13:        0x1032473e8 - daily::call_client::PyCallClient::set_video_renderer::h3fde43be49290836
  14:        0x103253704 - daily::call_client::PyCallClient::__pymethod_set_video_renderer__::h21c59fdbc3a9bee1
  15:        0x103244f40 - pyo3::impl_::trampoline::trampoline::ha7b289f845bbea05
  16:        0x10324808c - daily::call_client::<impl pyo3::impl_::pyclass::PyMethods<daily::call_client::PyCallClient> for pyo3::impl_::pyclass::PyClassImplCollector<daily::call_client::PyCallClient>>::py_methods::ITEMS::trampoline::hb727e7931c50ba83
  17:        0x100cecfa4 - _method_vectorcall_VARARGS_KEYWORDS
  18:        0x100e4b670 - __PyEval_EvalFrameDefault
  19:        0x100cdf844 - _method_vectorcall
  20:        0x101aa9ef8 - _pygi_signal_closure_marshal
  21:        0x101d201bc - _g_closure_invoke
  22:        0x101d378e4 - _signal_emit_unlocked_R
  23:        0x101d36af0 - _signal_emit_valist_unlocked
  24:        0x101d362fc - _g_signal_emit_valist
  25:        0x101d36e68 - _g_signal_emit
  26:        0x10590147c - __gtk_marshal_VOID__INT_DOUBLE_DOUBLEv
  27:        0x101d203b8 - __g_closure_invoke_va
  28:        0x101d3673c - _signal_emit_valist_unlocked
  29:        0x101d362fc - _g_signal_emit_valist
  30:        0x101d36e68 - _g_signal_emit
  31:        0x1059a2f9c - _gtk_gesture_click_end
  32:        0x101d235d0 - _g_cclosure_marshal_VOID__BOXEDv
  33:        0x101d203b8 - __g_closure_invoke_va
  34:        0x101d3673c - _signal_emit_valist_unlocked
  35:        0x101d362fc - _g_signal_emit_valist
  36:        0x101d36e68 - _g_signal_emit
  37:        0x1059a1b68 - __gtk_gesture_set_recognized
  38:        0x10599fb94 - __gtk_gesture_check_recognized
  39:        0x1059a1414 - _gtk_gesture_handle_event
  40:        0x1059a4780 - _gtk_gesture_single_handle_event
  41:        0x105975dbc - _gtk_event_controller_handle_event
  42:        0x105a9ead4 - _gtk_widget_run_controllers
  43:        0x105a9ed74 - __gtk_widget_captured_event
  44:        0x1059ddcac - _gtk_propagate_event_internal
  45:        0x1059dd654 - _gtk_main_do_event
  46:        0x105bf6338 - __gdk_marshal_BOOLEAN__POINTERv
  47:        0x105c427b4 - _gdk_surface_event_marshallerv
  48:        0x101d203b8 - __g_closure_invoke_va
  49:        0x101d3673c - _signal_emit_valist_unlocked
  50:        0x101d362fc - _g_signal_emit_valist
  51:        0x101d36e68 - _g_signal_emit
  52:        0x105c41a74 - _gdk_surface_handle_event
  53:        0x105bffd64 - _gdk_macos_event_source_dispatch
  54:        0x101e79418 - _g_main_context_dispatch_unlocked
  55:        0x101e79760 - _g_main_context_iterate_unlocked
  56:        0x101e797c0 - _g_main_context_iteration
  57:        0x102c54200 - _g_application_run
  58:        0x19ec4f050 - <unknown>
  59:        0x19ec57b04 - <unknown>
  60:        0x101aaad08 - _pygi_invoke_c_callable
  61:        0x101aabe04 - _pygi_function_cache_invoke
  62:        0x100e4fec8 - __PyEval_EvalFrameDefault
  63:        0x100e12a64 - _PyEval_EvalCode
  64:        0x100ec2ef0 - _run_mod
  65:        0x100ec2c6c - _pyrun_file
  66:        0x100ec2638 - __PyRun_SimpleFileObject
  67:        0x100ec1f1c - __PyRun_AnyFileObject
  68:        0x100eee318 - _pymain_run_file_obj
  69:        0x100eedcdc - _pymain_run_file
  70:        0x100eed320 - _Py_RunMain
  71:        0x100eee684 - _pymain_main
  72:        0x100c694e4 - _main
thread caused non-unwinding panic. aborting.
zsh: abort      RUST_BACKTRACE=1 python gtk_app.py
```

For the qt demo I get 
``` 
qt % RUST_BACKTRACE=1 python qt_app.py 
2024-12-09 17:13:29.857 python[82914:75052701] +[IMKClient subclass]: chose IMKClient_Modern
thread '<unnamed>' panicked at /Users/runner/actions-runner/_work/daily-x/daily-x/daily-core/src/native/ffi/call_client/participants.rs:345:64:
called `Result::unwrap()` on an `Err` value: Error(Char { character: 'T', index: 1 })
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: _daily_core_call_client_set_participant_video_renderer
   4: daily::call_client::PyCallClient::set_video_renderer
   5: daily::call_client::PyCallClient::__pymethod_set_video_renderer__
   6: pyo3::impl_::trampoline::trampoline
   7: daily::call_client::<impl pyo3::impl_::pyclass::PyMethods<daily::call_client::PyCallClient> for pyo3::impl_::pyclass::PyClassImplCollector<daily::call_client::PyCallClient>>::py_methods::ITEMS::trampoline
   8: _method_vectorcall_VARARGS_KEYWORDS
   9: __PyEval_EvalFrameDefault
  10: _method_vectorcall
  11: __ZL26callPythonMetaMethodHelperRK5QListI10QByteArrayEPKcPPvP7_object
  12: __ZN6PySide13SignalManager20callPythonMetaMethodE11QMetaMethodPPvP7_object
  13: __ZN20SignalManagerPrivate16qtMethodMetacallEP7QObjectiPPv
  14: __ZN11QMetaObject8activateEP7QObjectPKS_iPPv
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread '<unnamed>' panicked at core/src/panicking.rs:221:5:
panic in a function that cannot unwind
stack backtrace:
   0:        0x120f76e0c - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::habbf9c4f641febb1
   1:        0x120f943d4 - core::fmt::write::ha36a8060c13608ea
   2:        0x120f7411c - std::io::Write::write_fmt::h431832c8ebcc85c9
   3:        0x120f77f88 - std::panicking::default_hook::{{closure}}::h4aa1f60327dfff6a
   4:        0x120f77b38 - std::panicking::default_hook::h4ebc6eb4ae179807
   5:        0x120f78a04 - std::panicking::rust_panic_with_hook::h6a84efe4dcab239c
   6:        0x120f78408 - std::panicking::begin_panic_handler::{{closure}}::h5eef292190467fef
   7:        0x120f772d0 - std::sys::backtrace::__rust_end_short_backtrace::hd7e7925203f20af9
   8:        0x120f780f8 - _rust_begin_unwind
   9:        0x120fdb31c - core::panicking::panic_nounwind_fmt::hb2df5b6c3d6ab15b
  10:        0x120fdb394 - core::panicking::panic_nounwind::h6b53a509f430e184
  11:        0x120fdb480 - core::panicking::panic_cannot_unwind::hce6968fadcdebaaa
  12:        0x1203c49a0 - _daily_core_call_client_set_participant_video_renderer
  13:        0x1200073e8 - daily::call_client::PyCallClient::set_video_renderer::h3fde43be49290836
  14:        0x120013704 - daily::call_client::PyCallClient::__pymethod_set_video_renderer__::h21c59fdbc3a9bee1
  15:        0x120004f40 - pyo3::impl_::trampoline::trampoline::ha7b289f845bbea05
  16:        0x12000808c - daily::call_client::<impl pyo3::impl_::pyclass::PyMethods<daily::call_client::PyCallClient> for pyo3::impl_::pyclass::PyClassImplCollector<daily::call_client::PyCallClient>>::py_methods::ITEMS::trampoline::hb727e7931c50ba83
  17:        0x102a90fa4 - _method_vectorcall_VARARGS_KEYWORDS
  18:        0x102bef670 - __PyEval_EvalFrameDefault
  19:        0x102a83900 - _method_vectorcall
  20:        0x103a13668 - __ZL26callPythonMetaMethodHelperRK5QListI10QByteArrayEPKcPPvP7_object
  21:        0x103a12f00 - __ZN6PySide13SignalManager20callPythonMetaMethodE11QMetaMethodPPvP7_object
  22:        0x103a12c78 - __ZN20SignalManagerPrivate16qtMethodMetacallEP7QObjectiPPv
  23:        0x103b44110 - __ZN11QMetaObject8activateEP7QObjectPKS_iPPv
thread caused non-unwinding panic. aborting.
zsh: abort      RUST_BACKTRACE=1 python qt_app.py
```

**Comment by aconchillo** [comment]
I was able to run them just now (see images). Can you try again with 0.14.0? What version of Python are you running? I'm running Python 3.13.1 from Homebrew on macOS 14.5. I have created a venv and installed the dependencies for the demos as explained here: https://github.com/daily-co/daily-python/tree/main/demos

<img width="1432" alt="Screenshot 2024-12-19 at 7 09 48 PM" src="https://github.com/user-attachments/assets/881da501-d44d-4c88-bce3-547e7c627805" />
<img width="1392" alt="Screenshot 2024-12-19 at 7 09 31 PM" src="https://github.com/user-attachments/assets/9d0c7612-a91a-4930-91af-14df952b7e82" />

**Comment by ballagas** [comment]
Confirm that 0.14.0 seems to have resolved my issue.  More details about my environment.  
`
(base) MacBook-Pro daily-python % which python
/opt/homebrew/anaconda3/bin/python
(base) MacBook-Pro daily-python % python --version
Python 3.12.7
`
![Screenshot 2024-12-20 at 3 46 52 PM](https://github.com/user-attachments/assets/a1c9197c-5f03-44b6-9746-ec985a8d958f)

**Comment by ballagas** [comment]
However, I now I get a crash on connecting to a meeting:

```
(base) MacBook-Pro qt % RUST_BACKTRACE=1 python qt_app.py
2024-12-20 16:01:50.510 python[58827:7204511] +[IMKClient subclass]: chose IMKClient_Modern
thread '<unnamed>' panicked at /Users/runner/actions-runner/_work/daily-x/daily-x/daily-core/src/native/ffi/call_client/participants.rs:345:64:
called `Result::unwrap()` on an `Err` value: Error(Char { character: 'm', index: 1 })
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: _daily_core_call_client_set_participant_video_renderer
   4: daily::call_client::PyCallClient::set_video_renderer
   5: daily::call_client::PyCallClient::__pymethod_set_video_renderer__
   6: pyo3::impl_::trampoline::trampoline
   7: daily::call_client::<impl pyo3::impl_::pyclass::PyMethods<daily::call_client::PyCallClient> for pyo3::impl_::pyclass::PyClassImplCollector<daily::call_client::PyCallClient>>::py_methods::ITEMS::trampoline
   8: _method_vectorcall_VARARGS_KEYWORDS
   9: __PyEval_EvalFrameDefault
  10: _method_vectorcall
  11: __ZL26callPythonMetaMethodHelperRK5QListI10QByteArrayEPKcPPvP7_object
  12: __ZN6PySide13SignalManager20callPythonMetaMethodE11QMetaMethodPPvP7_object
  13: __ZN20SignalManagerPrivate16qtMethodMetacallEP7QObjectiPPv
  14: __ZN11QMetaObject8activateEP7QObjectPKS_iPPv
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread '<unnamed>' panicked at core/src/panicking.rs:221:5:
panic in a function that cannot unwind
stack backtrace:
   0:        0x10b18ae0c - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::habbf9c4f641febb1
   1:        0x10b1a83d4 - core::fmt::write::ha36a8060c13608ea
   2:        0x10b18811c - std::io::Write::write_fmt::h431832c8ebcc85c9
   3:        0x10b18bf88 - std::panicking::default_hook::{{closure}}::h4aa1f60327dfff6a
   4:        0x10b18bb38 - std::panicking::default_hook::h4ebc6eb4ae179807
   5:        0x10b18ca04 - std::panicking::rust_panic_with_hook::h6a84efe4dcab239c
   6:        0x10b18c408 - std::panicking::begin_panic_handler::{{closure}}::h5eef292190467fef
   7:        0x10b18b2d0 - std::sys::backtrace::__rust_end_short_backtrace::hd7e7925203f20af9
   8:        0x10b18c0f8 - _rust_begin_unwind
   9:        0x10b1ef31c - core::panicking::panic_nounwind_fmt::hb2df5b6c3d6ab15b
  10:        0x10b1ef394 - core::panicking::panic_nounwind::h6b53a509f430e184
  11:        0x10b1ef480 - core::panicking::panic_cannot_unwind::hce6968fadcdebaaa
  12:        0x10a5d89a0 - _daily_core_call_client_set_participant_video_renderer
  13:        0x10a21b3e8 - daily::call_client::PyCallClient::set_video_renderer::h3fde43be49290836
  14:        0x10a227704 - daily::call_client::PyCallClient::__pymethod_set_video_renderer__::h21c59fdbc3a9bee1
  15:        0x10a218f40 - pyo3::impl_::trampoline::trampoline::ha7b289f845bbea05
  16:        0x10a21c08c - daily::call_client::<impl pyo3::impl_::pyclass::PyMethods<daily::call_client::PyCallClient> for pyo3::impl_::pyclass::PyClassImplCollector<daily::call_client::PyCallClient>>::py_methods::ITEMS::trampoline::hb727e7931c50ba83
  17:        0x1002ccfa4 - _method_vectorcall_VARARGS_KEYWORDS
  18:        0x10042b670 - __PyEval_EvalFrameDefault
  19:        0x1002bf900 - _method_vectorcall
  20:        0x1022c3668 - __ZL26callPythonMetaMethodHelperRK5QListI10QByteArrayEPKcPPvP7_object
  21:        0x1022c2f00 - __ZN6PySide13SignalManager20callPythonMetaMethodE11QMetaMethodPPvP7_object
  22:        0x1022c2c78 - __ZN20SignalManagerPrivate16qtMethodMetacallEP7QObjectiPPv
  23:        0x1023f4110 - __ZN11QMetaObject8activateEP7QObjectPKS_iPPv
thread caused non-unwinding panic. aborting.
zsh: abort      RUST_BACKTRACE=1 python qt_app.py

```

**Comment by aconchillo** [comment]
Did you enter a `Participant ID`? It's actually mandatory. It should be the ID of a participant in the meeting. So, you can join your meeting from a browser. Then, in the browser console you can `enableDailyLogger()` and filter for `participant`. Then you can use that particpant ID in the application. Let me know if that works.

![image](https://github.com/user-attachments/assets/fea5edaf-75e9-4b19-bd48-5d22c82b33f8)

**Comment by mostafav7** [comment]
I keep getting this error: 

thread 'daily-emitter' panicked at /Users/daily/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-0.22.6/src/gil.rs:198:21:
assertion left != right failed: The Python interpreter is not initialized and the auto-initialize feature is not enabled.

Consider calling `pyo3::prepare_freethreaded_python()` before attempting to use Python APIs.
  left: 0
 right: 0
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
   4: std::sync::once::Once::call_once_force::{{closure}}
   5: std::sys::sync::once::queue::Once::call
   6: pyo3::gil::GILGuard::acquire
   7: daily::call_client::delegate::on_event_native
   8: daily_core::call_client::CallClient::_set_event_listener::{{closure}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'daily-emitter' panicked at core/src/panicking.rs:221:5:
panic in a function that cannot unwind
stack backtrace:
   0:        0x112792268 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h7adefaad4a31afc0
   1:        0x1127af440 - core::fmt::write::h381c0b0ce6ab972a
   2:        0x11278f4b4 - std::io::Write::write_fmt::h75af97148630d8d3
   3:        0x11279211c - std::sys::backtrace::BacktraceLock::print::h8baf33e22611de71
   4:        0x112793044 - std::panicking::default_hook::{{closure}}::h369c7295ef58c5b1
   5:        0x112792e88 - std::panicking::default_hook::h50746358288a9d6a
   6:        0x1127937f8 - std::panicking::rust_panic_with_hook::h7d795911432661cb
   7:        0x112793484 - std::panicking::begin_panic_handler::{{closure}}::h36f15310ecbde379
   8:        0x11279272c - std::sys::backtrace::__rust_end_short_backtrace::heed121414170e0c7
   9:        0x112793164 - _rust_begin_unwind
  10:        0x1127f8b9c - core::panicking::panic_nounwind_fmt::h5d86a478a9d7437c
  11:        0x1127f8c14 - core::panicking::panic_nounwind::he171ad52d328e60b
  12:        0x1127f8d00 - core::panicking::panic_cannot_unwind::h2dd8cd735765e065
  13:        0x11181df40 - daily::call_client::delegate::on_event_native::h090981fc6608f395
  14:        0x1119897c4 - daily_core::call_client::CallClient::_set_event_listener::{{closure}}::h78e6573fd85f3be0
  15:        0x1119e30f0 - std::sys::backtrace::__rust_begin_short_backtrace::h9b70b34f9443ffab
  16:        0x1119ea194 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h20b6f745919e3266
  17:        0x112795278 - std::sys::pal::unix::thread::Thread::new::thread_start::h44ebc83f14222f58
  18:        0x19192ef94 - __pthread_joiner_wake
thread caused non-unwinding panic. aborting.
zsh: abort    python test_daily.py


when running the following basic script as stated in their demos. 

`from daily import *
Daily.init()
client = CallClient()
#client.join("https://api.daily.co/v1/rooms/<room_is>", meeting_token = <my token>)`


I tried with different python versions and on macOS and linux and always getting the same error. How can I solve this issue?

**Comment by ballagas** [comment]
I was using my name as a "Participant ID".  I just attempted to extract a participant ID using the browser console, but it didn't seem to work for me: 
![Screenshot 2025-01-05 at 4 22 50 PM](https://github.com/user-attachments/assets/8d3a0ba4-c43f-4e48-a1b3-0b59304b8089)

**Comment by ballagas** [comment]
I figured out that I needed to enable the verbose level of debugging so that it shows "All levels" next to the filter.  Now with a valid Participant ID, the demo app seems to be working.  I am a little confused about why the demo UI requires a Participant ID, isn't the participant ID automatically assigned when joining a call?  E.g. on this line: https://github.com/daily-co/daily-python/blob/22a15503523676f74f31bfc76b10825a8d4a9aed/demos/qt/qt_app.py#L138

**Comment by ballagas** [comment]
I was able to answer my own question.  The demo app is structured such that 'Participant ID' represents the stream of the remote participant you are interested in subscribing to.  With a slight refactor of the app, you can automatically retrieve the remote participant id using the event_handler callback.  I'd be happy to create a merge request with the changes if desired.

**Comment by mattieruth** [comment]
I'm not sure I completely follow this whole thread, but merge requests are always welcome!

**Comment by aconchillo** [comment]
> I was able to answer my own question. The demo app is structured such that 'Participant ID' represents the stream of the remote participant you are interested in subscribing to. With a slight refactor of the app, you can automatically retrieve the remote participant id using the event_handler callback. I'd be happy to create a merge request with the changes if desired.

That is exactly right. The application goal is to show the participant ID. It could be done automatically if there was only a single participant, which for an example is probably fine.
